### ISSUE TITLE
tools assume R_ASXXXx1 for the protocol

### ISSUE THREAD

**Issue by slampt** [dowlingw/bird-tool#11]
So what if you have multiple sessions for one AS and I am using different protocol names. E.G R_ASXXXx2 for the second session.. Please fix kthx <3

**Comment by dowlingw** [comment]
@slampt - I've pushed up a new branch `feature-secondary` which should allow the script to work with secondary sessions for a given Peer AS.

Whilst I've eyeballed the code, there are still a few things that would need to be ironed out, particularly options combined with `-a ASNUM`.

Here's a list of known issues which need input/clarification:

* Using `-x` and `-a ASNUM` together will display prefixes accepted across any session for an AS, and will include an AS each time it appears on a session. I'd combine these, however it's possible that the ASPath (which can be shown with `-j`) will be different on either peer due to prepending/etc.
* Using `-n` will show only the AS number of the broken peering session, not the session name - so it won't be clear which session broke, unless it's both in which case you'd see the entry twice. Should this show session name instead?
* Using `-n` in combination with `-a` will return an exit code based on the first session it comes across in Birdctl output. This will be a bit fiddly, but some guidance on what you'd expect it to do in this case wouldn't go astray - otherwise this is a TODO before this code can be considered done.

I think that's it, if we can resolve the three above issues then I'll ask for some assistance testing. If we're OK, then maybe we can merge this into master.

Thoughts?

**Comment by dowlingw** [comment]
Ok had a bit more of a think about these use cases:
* `-x -a ASNUM` it is safe to remove duplicate prefixes here.
* `-x -j -a ASNUM` it is not safe to remove duplicate prefixes if they have a different ASPath
* `-n` seems like a good idea to show session name, so I'll do that
* `-n -a` TBA.

Doing the first three now.

**Comment by dowlingw** [comment]
Okay, to solve the case of `-n -a ASNUM`, I can remove the custom code and make it work the exact same way as `-n` normally, but `-a` would avoid populating the nagios results for any AS other than the one specified.

Not entirely sure why I didn't write it this way in the first place to be honest...

**Comment by dowlingw** [comment]
Okay @slampt - I think this might be ready for some serious testing.
Reckon you can grab the code in the branch and see how the new behaviour works for you?

Cheers :)

**Comment by dowlingw** [comment]
Will need to check cacti/scripts/bird_peerinfo.pl as well.

**Comment by dowlingw** [comment]
Doing some testing on this one.

* `-l` does not return a list of unique ASNs, fix
* `-n` just need to run that past someone using it as the output has changed (see below)
* `-x` has a pretty bad bug, looks like it's only returning 1 prefix per AS. Using `-a` shows that prefixes are still attributed correctly.

````
root@rs1:~/test# ~/bird-tool/bird_query.pl -a 132240 -n
SESSIONS OK: Unknown=0; Warning=0; Up=2; Down=0.
root@rs1:~/test# /opt/bird-tools/bin/bird_query.pl -a 132240 -n
AS132240 OK: Established
````

**Comment by dowlingw** [comment]
This has now been merged into master, any issues will now be treated as bugs.
